interface IFont {
  id: string;
  value: string;
  label: string;
}

export function getFonts(): IFont[] {
  const selectedFamilies = [
    "Roboto, sans-serif",
    "Open Sans, sans-serif",
    "Lato, sans-serif",
    "Montserrat, sans-serif",
    "Poppins, sans-serif",
    "Inter, sans-serif",
    "Oswald, sans-serif",
    "Raleway, sans-serif",
    "Noto Sans, sans-serif",
    "Roboto Condensed, sans-serif",
    "Nunito, sans-serif",
    "Work Sans, sans-serif",
    "Rubik, sans-serif",
    "Mukta, sans-serif",
    "Ubuntu, sans-serif",
    "Quicksand, sans-serif",
    "Hind, sans-serif",
    "Fira Sans, sans-serif",
    "Barlow, sans-serif",
    "Cabin, sans-serif",
    "Prompt, sans-serif",
    "Heebo, sans-serif",
    "Source Sans 3, sans-serif",
    "Titillium Web, sans-serif",
    "Muli, sans-serif",
    "Manrope, sans-serif",
    "Josefin Sans, sans-serif",
    "Karla, sans-serif",
    "DM Sans, sans-serif",
    "PT Sans, sans-serif",
    "Tajawal, sans-serif",
    "Public Sans, sans-serif",
    "Catamaran, sans-serif",
    "Urbanist, sans-serif",
    "Outfit, sans-serif",
    "Lexend, sans-serif",
    "Signika, sans-serif",
    "Asap, sans-serif",
    "Sarabun, sans-serif",
    "Red Hat Display, sans-serif",
    "Exo 2, sans-serif",
    "Sen, sans-serif",
    "Epilogue, sans-serif",
    "Jost, sans-serif",
    "IBM Plex Sans, sans-serif",
    "Varela Round, sans-serif",
    "Mulish, sans-serif",
    "Spartan, sans-serif",
    "Krub, sans-serif",
    "Questrial, sans-serif",
    "Barlow Condensed, sans-serif",
    "Overpass, sans-serif",
    "Alata, sans-serif",
    "Kanit, sans-serif",
    "Noto Serif, serif",
    "Merriweather, serif",
    "Playfair Display, serif",
    "Lora, serif",
    "Cormorant Garamond, serif",
    "EB Garamond, serif",
    "PT Serif, serif",
    "Libre Baskerville, serif",
    "DM Serif Display, serif",
    "Crimson Text, serif",
    "Bitter, serif",
    "Spectral, serif",
    "Cormorant, serif",
    "Zilla Slab, serif",
    "Nanum Myeongjo, serif",
    "Tinos, serif",
    "Cardo, serif",
    "Domine, serif",
    "Arvo, serif",
    "Vollkorn, serif",
    "Bree Serif, serif",
    "Alegreya, serif",
    "Noticia Text, serif",
    "Libre Caslon Text, serif",
    "Faustina, serif",
    "Mate, serif",
    "Lusitana, serif",
    "Arapey, serif",
    "Fira Sans Condensed, sans-serif",
    "Assistant, sans-serif",
    "Space Grotesk, sans-serif",
    "Sofia Sans, sans-serif",
    "Niramit, sans-serif",
    "Be Vietnam Pro, sans-serif",
    "Eczar, serif",
    "Quattrocento, serif",
    "Rokkitt, serif",
    "Cormorant Infant, serif",
    "Slabo 27px, serif",
    "Ultra, serif",
    "Rozha One, serif",
    "Old Standard TT, serif",
    "Baskervville, serif",
    "Play, sans-serif",
    "Mada, sans-serif",
    "Rajdhani, sans-serif",
    "Cabinet Grotesk, sans-serif",
    "Archivo, sans-serif",
    "Anton, display",
    "Bebas Neue, display",
    "Abril Fatface, display",
    "Alfa Slab One, display",
    "Righteous, display",
    "Lobster, display",
    "Pacifico, handwriting",
    "Caveat, handwriting",
    "Dancing Script, handwriting",
    "Great Vibes, handwriting",
    "Satisfy, handwriting",
    "Shadows Into Light, handwriting",
    "Cookie, handwriting",
    "Gloria Hallelujah, handwriting",
    "Indie Flower, handwriting",
    "Courgette, handwriting",
    "Amatic SC, display",
    "Fredoka, sans-serif",
    "Baloo 2, display",
    "Chewy, display",
    "Luckiest Guy, display",
    "Permanent Marker, handwriting",
    "Architects Daughter, handwriting",
    "Rock Salt, handwriting",
    "Handlee, handwriting",
    "Kaushan Script, handwriting",
    "Patrick Hand, handwriting",
    "Carter One, display",
    "Sigmar, display",
    "Rye, display",
    "Black Ops One, display",
    "Bungee, display",
    "Press Start 2P, monospace",
    "Space Mono, monospace",
    "Fira Code, monospace",
    "Roboto Mono, monospace",
    "JetBrains Mono, monospace",
    "Inconsolata, monospace",
    "Share Tech Mono, monospace",
    "Cutive Mono, monospace",
    "Major Mono Display, monospace",
    "Source Code Pro, monospace",
    "Audiowide, display",
    "Syncopate, display",
    "Unica One, display",
    "Orbitron, display",
    "Chakra Petch, sans-serif",
    "Expletus Sans, display",
    "Staatliches, display",
    "Poiret One, display",
    "Aldrich, sans-serif",
    "Gruppo, display",
    "Viga, sans-serif",
    "Suez One, serif",
    "Frank Ruhl Libre, serif",
    "Cambo, serif",
    "Marcellus, serif",
    "Cinzel, serif",
    "Judson, serif",
    "Gelasio, serif",
    "Abhaya Libre, serif",
    "Cormorant SC, serif",
    "Crimson Pro, serif",
    "Noto Serif Display, serif",
    "Sanchez, serif",
    "DM Serif Text, serif",
    "Fjord One, serif",
    "Suranna, serif",
    "Cardo, serif",
    "Kreon, serif",
    "Cormorant Upright, serif",
    "Gloock, serif",
    "Julius Sans One, sans-serif",
    "Assistant, sans-serif",
    "Encode Sans, sans-serif",
    "Nanum Gothic, sans-serif",
    "Maven Pro, sans-serif",
    "Overpass Mono, monospace",
    "Noto Sans Display, sans-serif",
    "Albert Sans, sans-serif",
    "Palanquin, sans-serif",
    "Chivo, sans-serif",
    "Arimo, sans-serif",
    "Exo, sans-serif",
    "Molengo, sans-serif",
    "Abel, sans-serif",
    "Teko, sans-serif",
    "Saira, sans-serif",
    "Jura, sans-serif",
    "Kumbh Sans, sans-serif",
    "Hepta Slab, serif",
    "Azeret Mono, monospace",
    "League Spartan, sans-serif",
    "Rufina, serif",
    "Cinzel Decorative, display",
    "Crete Round, serif",
    "Amiri, serif",
    "Spectral SC, serif",
    "Petrona, serif",
    "Neuton, serif",
    "Coustard, serif",
    "Vidaloka, serif",
    "Bellefair, serif",
    "Antic Slab, serif",
    "Copse, serif",
    "DM Mono, monospace",
    "Anonymous Pro, monospace",
    "Oxygen Mono, monospace",
    "Courier Prime, monospace",
    "IBM Plex Mono, monospace",
    "Zilla Slab Highlight, display",
    "Shrikhand, display",
    "Bungee Shade, display",
    "Fugaz One, display",
    "Monoton, display",
    "Rammetto One, display",
    "Cinzel Decorative, display",
    "Fascinate Inline, display",
    "Racing Sans One, display",
    "Lilita One, display",
    "Potta One, display",
    "Tourney, display",
    "Cherry Swash, display",
    "Creepster, display",
    "Butcherman, display",
    "Ewert, display",
    "Bowlby One SC, display",
    "Galindo, display",
    "Knewave, display",
    "Fredoka One, display",
    "Ranchers, display",
    "Codystar, display",
    "Press Start 2P, monospace",
    "VT323, monospace",
    "Cutive Mono, monospace",
    "IBM Plex Serif, serif",
    "Philosopher, sans-serif",
    "Noto Sans JP, sans-serif",
    "Noto Sans KR, sans-serif",
    "Noto Sans Thai, sans-serif",
    "Noto Serif JP, serif",
    "Noto Serif KR, serif",
    "Noto Serif SC, serif",
    "Noto Serif TC, serif",
  ];
  return selectedFamilies.sort().map((font: string) => {
    return {
      id: font,
      value: font,
      label: font.split(",")[0],
    };
  });
}
